version: '3'

services:

  LWE450-TGTD:
    image: ghcr.io/mo-rise/crowsnest-toolbox:v0.4.2
    restart: always
    network_mode: "host"
    command:
      [
        "udp_listen --encode multicast 239.192.0.2 60002 --interface=<interface ip> | raw_to_brefv | mosquitto_pub -l -t '<topic>'"
      ]

  LWE450-SATD:
    image: ghcr.io/mo-rise/crowsnest-toolbox:v0.4.2
    restart: always
    network_mode: "host"
    command:
      [
        "udp_listen --encode multicast 239.192.0.3 60003 --interface=<interface ip> | raw_to_brefv | mosquitto_pub -l -t '<topic>'"
      ]

  LWE450-NAVD:
    image: ghcr.io/mo-rise/crowsnest-toolbox:v0.4.2
    restart: always
    network_mode: "host"
    command:
      [
        "udp_listen --encode multicast 239.192.0.4 60004 --interface=<interface ip> | raw_to_brefv | mosquitto_pub -l -t '<topic>'"
      ]
